// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package api_pb // import "github.com/sloppycoder/ngms/accounts/api"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/empty"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Balance_Type int32

const (
	Balance_CURRENT   Balance_Type = 0
	Balance_AVAILABLE Balance_Type = 1
)

var Balance_Type_name = map[int32]string{
	0: "CURRENT",
	1: "AVAILABLE",
}
var Balance_Type_value = map[string]int32{
	"CURRENT":   0,
	"AVAILABLE": 1,
}

func (x Balance_Type) String() string {
	return proto.EnumName(Balance_Type_name, int32(x))
}
func (Balance_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_account_13b913bd06d5b13d, []int{1, 0}
}

type Account struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId            string     `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ProdCode             string     `protobuf:"bytes,3,opt,name=prod_code,json=prodCode,proto3" json:"prod_code,omitempty"`
	ProdName             string     `protobuf:"bytes,4,opt,name=prod_name,json=prodName,proto3" json:"prod_name,omitempty"`
	Balances             []*Balance `protobuf:"bytes,5,rep,name=balances,proto3" json:"balances,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_13b913bd06d5b13d, []int{0}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (dst *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(dst, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *Account) GetProdCode() string {
	if m != nil {
		return m.ProdCode
	}
	return ""
}

func (m *Account) GetProdName() string {
	if m != nil {
		return m.ProdName
	}
	return ""
}

func (m *Account) GetBalances() []*Balance {
	if m != nil {
		return m.Balances
	}
	return nil
}

type Balance struct {
	Amount               float64              `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Type                 Balance_Type         `protobuf:"varint,2,opt,name=type,proto3,enum=ngms.accounts.Balance_Type" json:"type,omitempty"`
	CreditFlag           bool                 `protobuf:"varint,3,opt,name=credit_flag,json=creditFlag,proto3" json:"credit_flag,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,4,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Balance) Reset()         { *m = Balance{} }
func (m *Balance) String() string { return proto.CompactTextString(m) }
func (*Balance) ProtoMessage()    {}
func (*Balance) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_13b913bd06d5b13d, []int{1}
}
func (m *Balance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Balance.Unmarshal(m, b)
}
func (m *Balance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Balance.Marshal(b, m, deterministic)
}
func (dst *Balance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Balance.Merge(dst, src)
}
func (m *Balance) XXX_Size() int {
	return xxx_messageInfo_Balance.Size(m)
}
func (m *Balance) XXX_DiscardUnknown() {
	xxx_messageInfo_Balance.DiscardUnknown(m)
}

var xxx_messageInfo_Balance proto.InternalMessageInfo

func (m *Balance) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Balance) GetType() Balance_Type {
	if m != nil {
		return m.Type
	}
	return Balance_CURRENT
}

func (m *Balance) GetCreditFlag() bool {
	if m != nil {
		return m.CreditFlag
	}
	return false
}

func (m *Balance) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type GetAccountRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountRequest) Reset()         { *m = GetAccountRequest{} }
func (m *GetAccountRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountRequest) ProtoMessage()    {}
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_13b913bd06d5b13d, []int{2}
}
func (m *GetAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountRequest.Unmarshal(m, b)
}
func (m *GetAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountRequest.Marshal(b, m, deterministic)
}
func (dst *GetAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountRequest.Merge(dst, src)
}
func (m *GetAccountRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountRequest.Size(m)
}
func (m *GetAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountRequest proto.InternalMessageInfo

func (m *GetAccountRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func init() {
	proto.RegisterType((*Account)(nil), "ngms.accounts.Account")
	proto.RegisterType((*Balance)(nil), "ngms.accounts.Balance")
	proto.RegisterType((*GetAccountRequest)(nil), "ngms.accounts.GetAccountRequest")
	proto.RegisterEnum("ngms.accounts.Balance_Type", Balance_Type_name, Balance_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*Account, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/ngms.accounts.AccountService/GetAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	GetAccount(context.Context, *GetAccountRequest) (*Account, error)
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ngms.accounts.AccountService/GetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetAccount(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ngms.accounts.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccount",
			Handler:    _AccountService_GetAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_account_13b913bd06d5b13d) }

var fileDescriptor_account_13b913bd06d5b13d = []byte{
	// 444 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x4f, 0x8e, 0xd3, 0x30,
	0x18, 0xc5, 0x49, 0xa7, 0x4c, 0xdb, 0x2f, 0xb4, 0x1a, 0xbc, 0xa8, 0xa2, 0x16, 0x98, 0x2a, 0xab,
	0x59, 0xd9, 0x22, 0x2c, 0x11, 0x8b, 0x76, 0x34, 0xa0, 0x91, 0x46, 0xb3, 0x30, 0x1d, 0x16, 0x6c,
	0x22, 0x27, 0x76, 0x83, 0xa5, 0x24, 0x36, 0x89, 0x83, 0xa8, 0x10, 0x1b, 0xae, 0xc0, 0x1d, 0xb8,
	0x10, 0x12, 0x27, 0xe0, 0x20, 0x28, 0x8e, 0x3b, 0x15, 0x81, 0x65, 0xde, 0xef, 0x7d, 0xff, 0x9e,
	0x03, 0x53, 0x96, 0xa6, 0xaa, 0x29, 0x0d, 0xd6, 0x95, 0x32, 0x0a, 0x4d, 0xcb, 0xac, 0xa8, 0xb1,
	0xd3, 0xea, 0xc5, 0x79, 0xa6, 0x54, 0x96, 0x0b, 0x62, 0x61, 0xd2, 0xec, 0x88, 0x91, 0x85, 0xa8,
	0x0d, 0x2b, 0x74, 0xe7, 0x5f, 0x3c, 0x71, 0x06, 0xa6, 0x25, 0x61, 0x65, 0xa9, 0x0c, 0x33, 0x52,
	0x95, 0xb5, 0xa3, 0xcb, 0x7e, 0xb9, 0x28, 0xb4, 0xd9, 0x77, 0x30, 0xfc, 0xe1, 0xc1, 0x68, 0xdd,
	0x0d, 0x42, 0x33, 0x18, 0x48, 0x1e, 0x78, 0x2b, 0xef, 0x62, 0x42, 0x07, 0x92, 0xa3, 0xa7, 0x00,
	0x6e, 0x87, 0x58, 0xf2, 0x60, 0x60, 0xf5, 0x89, 0x53, 0xae, 0x39, 0x5a, 0xc2, 0x44, 0x57, 0x8a,
	0xc7, 0xa9, 0xe2, 0x22, 0x38, 0xb1, 0x74, 0xdc, 0x0a, 0x97, 0x8a, 0x8b, 0x7b, 0x58, 0xb2, 0x42,
	0x04, 0xc3, 0x23, 0xbc, 0x65, 0x85, 0x40, 0x11, 0x8c, 0x13, 0x96, 0xb3, 0x32, 0x15, 0x75, 0xf0,
	0x70, 0x75, 0x72, 0xe1, 0x47, 0x73, 0xfc, 0xd7, 0xc9, 0x78, 0xd3, 0x61, 0x7a, 0xef, 0x0b, 0x7f,
	0x79, 0x30, 0x72, 0x2a, 0x9a, 0xc3, 0x29, 0x2b, 0x5a, 0xa3, 0x5d, 0xd6, 0xa3, 0xee, 0x0b, 0x11,
	0x18, 0x9a, 0xbd, 0x16, 0x76, 0xd5, 0x59, 0xb4, 0xfc, 0x7f, 0x4f, 0xbc, 0xdd, 0x6b, 0x41, 0xad,
	0x11, 0x9d, 0x83, 0x9f, 0x56, 0x82, 0x4b, 0x13, 0xef, 0x72, 0x96, 0xd9, 0x23, 0xc6, 0x14, 0x3a,
	0xe9, 0x75, 0xce, 0x32, 0xf4, 0x0a, 0x1e, 0xe5, 0xac, 0x36, 0x71, 0xa3, 0x39, 0x33, 0x82, 0xdb,
	0x4b, 0xfc, 0x68, 0x81, 0xbb, 0x48, 0xf1, 0x21, 0x52, 0xbc, 0x3d, 0xbc, 0x08, 0xf5, 0x5b, 0xff,
	0x5d, 0x67, 0x0f, 0x43, 0x18, 0xb6, 0xd3, 0x90, 0x0f, 0xa3, 0xcb, 0x3b, 0x4a, 0xaf, 0x6e, 0xb7,
	0x67, 0x0f, 0xd0, 0x14, 0x26, 0xeb, 0x77, 0xeb, 0xeb, 0x9b, 0xf5, 0xe6, 0xe6, 0xea, 0xcc, 0x0b,
	0x23, 0x78, 0xfc, 0x46, 0x18, 0xf7, 0x06, 0x54, 0x7c, 0x6c, 0x44, 0x6d, 0x7a, 0xd1, 0x7b, 0xbd,
	0xe8, 0xa3, 0xcf, 0x30, 0x73, 0x05, 0x6f, 0x45, 0xf5, 0x49, 0xa6, 0x02, 0xed, 0x00, 0x8e, 0x5d,
	0xd0, 0xaa, 0x77, 0xfa, 0x3f, 0x03, 0x16, 0xfd, 0xc0, 0x1d, 0x0e, 0x9f, 0x7d, 0xfb, 0xf9, 0xfb,
	0xfb, 0x20, 0x40, 0x73, 0x72, 0x40, 0xe4, 0xcb, 0x71, 0x93, 0xaf, 0x9b, 0xe7, 0xef, 0x49, 0x26,
	0xcd, 0x87, 0x26, 0xc1, 0xa9, 0x2a, 0x48, 0x9d, 0x2b, 0xad, 0xf7, 0xed, 0x0f, 0x50, 0x91, 0xb6,
	0xdf, 0xb1, 0x88, 0x69, 0xf9, 0x92, 0x69, 0x19, 0xeb, 0x24, 0x39, 0xb5, 0x29, 0xbd, 0xf8, 0x13,
	0x00, 0x00, 0xff, 0xff, 0x99, 0xb5, 0x3a, 0x35, 0xe5, 0x02, 0x00, 0x00,
}
