apiVersion: v1
kind: Service
metadata:
  name: locust
spec:
  ports:
    - port: 8089
      name: http
  type: NodePort
  selector:
    app: locust

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust
spec:
  selector:
    matchLabels:
      app: locust
  template:
    metadata:
      labels:
        app: locust
    spec:
      containers:
        - name: locust
          image: gcr.io/k8s-skaffold/skaffold-locust
#          env:
#          - name: SLAVE_PROTO
#            value: rest