apiVersion: v1
kind: Service
metadata:
  name: account
spec:
  ports:
    - port: 3000
      name: http
    - port: 3001
      name: grpc
    - port: 3002
      name: metrics
  type: NodePort
  selector:
    app: account

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
spec:
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: gcr.io/k8s-skaffold/skaffold-account
          ports:
            - containerPort: 3000
            - containerPort: 3001
