apiVersion: v1
kind: Service
metadata:
  name: accounts-api
  labels:
    app: accounts-api
    svc-group: api
spec:
  ports:
    - port: 3000
      name: web
    - port: 3001
      name: grpc
  type: NodePort
  selector:
    app: accounts-api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-api
spec:
  selector:
    matchLabels:
      app: accounts-api
  template:
    metadata:
      labels:
        app: accounts-api
    spec:
      containers:
        - name: accounts-api
          image: gcr.io/k8s-skaffold/skaffold-account
