name: publish docker images

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build account service
        uses: actions/docker/cli@master
        with:
          args: build -t docker.pkg.github.com/sloppycoder/ngms/account-svc:latest accounts/

      - name: Build locust tester
        uses: actions/docker/cli@master
        with:
          args: build -t docker.pkg.github.com/sloppycoder/ngms/benchmark:latest benchmark/

      - name: Docker Login
        uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: sloppycoder
          DOCKER_PASSWORD: ${{ secrets.GITHUB_PASS }}
          DOCKER_REGISTRY_URL: "docker.pkg.github.com"

      - name: Push image account-svc
        uses: actions/docker/cli@master
        with:
          args: push docker.pkg.github.com/sloppycoder/ngms/account-svc:latest

      - name: Push image benchmark
        uses: actions/docker/cli@master
        with:
          args: push docker.pkg.github.com/sloppycoder/ngms/benchmark:latest

