name: Docker Image CI

on: 
  push:
    branches:
      - master

jobs:

  build:
 
    runs-on: ubuntu-latest
    branch: master
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        cd accounts
        docker build . --tag hub.docker.com/sloppycoder/ngms-account-svc:$(date +%s)
        cd ..
        cd benchmark
        docker build . --tag hub.docker.com/sloppycoder/ngms-locust:$(date +%s)
        cd ..
