name: publish docker images

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build account service
        uses: actions/docker/cli@master
        with:
          args: build -t sloppycoder/ngms-account-svc:latest accounts/

      - name: Build locust tester
        uses: actions/docker/cli@master
        with:
          args: build -t sloppycoder/ngms-locust:latest benchmark/

      - name: Docker Login
        uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: sloppycoder
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASS }}

      - name: Push image account-svc
        uses: actions/docker/cli@master
        with:
          args: push sloppycoder/ngms-account-svc:latest

      - name: Push image locust
        uses: actions/docker/cli@master
        with:
          args: push sloppycoder/ngms-locust:latest

