name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker image registry
        uses: actions/docker/login@master
        env:
          DOCKER_REGISTRY_URL: registry.hub.docker.com
          DOCKER_USERNAME: sloppycoder
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASS }}

      - uses: actions/checkout@v1

      - name: Build the Docker image
        run: |
          cd accounts
          docker build . --tag hub.docker.com/sloppycoder/ngms-account-svc:latest
          docker push hub.docker.com/sloppycoder/ngms-account-svc:lastest
          cd ..

          cd benchmark
          docker build . --tag hub.docker.com/sloppycoder/ngms-locust:latest
          docker push hub.docker.com/sloppycoder/ngms-locust:latest
          cd ..
