name: publish docker images

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build the Docker image
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASS }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u sloppycoder --password-stdin

          cd accounts
          docker build . --tag sloppycoder/ngms-account-svc:latest
          docker push sloppycoder/ngms-account-svc:latest
          cd ..

          cd benchmark
          docker build . --tag sloppycoder/ngms-locust:latest && docker push sloppycoder/ngms-locust:latest
          cd ..

          docker logout